// Package regions returns a simple map of 3 letter region codes against their
// full region names.
package regions

// Regions returns the mapping of region names to codes
func Regions() map[string]string {
	m := map[string]string{
		"ALA": "Aland Islands",
		"AFG": "Afghanistan",
		"ALB": "Albania",
		"DZA": "Algeria",
		"ASM": "American Samoa",
		"AND": "Andorra",
		"AGO": "Angola",
		"AIA": "Anguilla",
		"ATA": "Antarctica",
		"ATG": "Antigua and Barbuda",
		"ARG": "Argentina",
		"ARM": "Armenia",
		"ABW": "Aruba",
		"AUS": "Australia",
		"AUT": "Austria",
		"AZE": "Azerbaijan",
		"BHS": "Bahamas",
		"BHR": "Bahrain",
		"BGD": "Bangladesh",
		"BRB": "Barbados",
		"BLR": "Belarus",
		"BEL": "Belgium",
		"BLZ": "Belize",
		"BEN": "Benin",
		"BMU": "Bermuda",
		"BTN": "Bhutan",
		"BOL": "Bolivia",
		"BIH": "Bosnia and Herzegowina",
		"BWA": "Botswana",
		"BVT": "Bouvet Island",
		"BRA": "Brazil",
		"IOT": "British Indian Ocean Territory",
		"BRN": "Brunei Darussalam",
		"BGR": "Bulgaria",
		"BFA": "Burkina Faso",
		"BDI": "Burundi",
		"KHM": "Cambodia",
		"CMR": "Cameroon",
		"CAN": "Canada",
		"CPV": "Cape Verde",
		"CYM": "Cayman Islands",
		"CAF": "Central African Republic",
		"TCD": "Chad",
		"CHL": "Chile",
		"CHN": "China",
		"CXR": "Christmas Island",
		"CCK": "Cocos (Keeling) Islands",
		"COL": "Colombia",
		"COM": "Comoros",
		"COG": "Congo",
		"COD": "Democratic Rep of Congo",
		"COK": "Cook Islands",
		"CRI": "Costa Rica",
		"CIV": "Cote D'Ivoire",
		"HRV": "Croatia",
		"CUW": "Curacao",
		"CUB": "Cuba",
		"CYP": "Cyprus",
		"CZE": "Czech Republic",
		"DNK": "Denmark",
		"DJI": "Djibouti",
		"DMA": "Dominica",
		"DOM": "Dominican Republic",
		"ECU": "Ecuador",
		"EGY": "Egypt",
		"SLV": "El Salvador",
		"GNQ": "Equatorial Guinea",
		"ERI": "Eritrea",
		"EST": "Estonia",
		"ETH": "Ethiopia",
		"FLK": "Falkland Islands (Malvinas)",
		"FRO": "Faroe Islands",
		"FJI": "Fiji",
		"FIN": "Finland",
		"FRA": "France",
		"GUF": "French Guiana",
		"PYF": "French Polynesia",
		"ATF": "French Southern Territories",
		"GAB": "Gabon",
		"GMB": "Gambia",
		"GEO": "Georgia",
		"DEU": "Germany",
		"GHA": "Ghana",
		"GIB": "Gibraltar",
		"GRC": "Greece",
		"GRL": "Greenland",
		"GRD": "Grenada",
		"GLP": "Guadeloupe",
		"GUM": "Guam",
		"GTM": "Guatemala",
		"GGY": "Guernsey",
		"GIN": "Guinea",
		"GNB": "Guinea-Bissau",
		"GUY": "Guyana",
		"HTI": "Haiti",
		"HMD": "Heard and Mc Donald Islands",
		"VAT": "Holy See (Vatican city state)",
		"HND": "Honduras",
		"HKG": "Hong kong",
		"HUN": "Hungary",
		"ISL": "Iceland",
		"IND": "India",
		"IDN": "Indonesia",
		"IRN": "Iran",
		"IRQ": "Iraq",
		"IRL": "Ireland",
		"IMN": "Isle of man",
		"ISR": "Israel",
		"ITA": "Italy",
		"JAM": "Jamaica",
		"JPN": "Japan",
		"JEY": "Jersey",
		"JOR": "Jordan",
		"KAZ": "Kazakhstan",
		"KEN": "Kenya",
		"KIR": "Kiribati",
		"KOR": "Korea, Republic of",
		"KWT": "Kuwait",
		"KGZ": "Kyrgyzstan",
		"LVA": "Latvia",
		"LAO": "Laos",
		"LBN": "Lebanon",
		"LSO": "Lesotho",
		"LBR": "Liberia",
		"LBY": "Libyan Arab Jamahuriya",
		"LIE": "Liechtenstein",
		"LTU": "Lithuania",
		"LUX": "Luxembourg",
		"MAC": "Macao",
		"MKD": "Macedonia",
		"MDG": "Madagascar",
		"MWI": "Malawi",
		"MYS": "Malaysia",
		"MDV": "Maldives",
		"MLI": "Mali",
		"MLT": "Malta",
		"MHL": "Marshall Islands",
		"MTQ": "Martinique",
		"MRT": "Mauritania",
		"MUS": "Mauritius",
		"MYT": "Mayotte",
		"MEX": "Mexico",
		"FSM": "Micronesia",
		"MDA": "Moldova",
		"MCO": "Monaco",
		"MNG": "Mongolia",
		"MNE": "Montenegro",
		"MSR": "Montserrat",
		"MAR": "Morocco",
		"MOZ": "Mozambique",
		"MMR": "Myanmar",
		"NAM": "Namibia",
		"NRU": "Nauru",
		"NPL": "Nepal",
		"NLD": "Netherlands",
		"ANT": "Netherlands Antilles",
		"NCL": "New Caledonia",
		"NZL": "New Zealand",
		"NIC": "Nicaragua",
		"NER": "Niger",
		"NGA": "Nigeria",
		"NIU": "Niue",
		"NFK": "Norfolk Island",
		"MNP": "Northern Mariana Islands",
		"NOR": "Norway",
		"OMN": "Oman",
		"PAK": "Pakistan",
		"PLW": "Palau",
		"PAN": "Panama",
		"PNG": "Papua New Guinea",
		"PRY": "Paraguay",
		"PER": "Peru",
		"PHL": "Philippines",
		"PCN": "Pitcairn",
		"POL": "Poland",
		"PRT": "Portugal",
		"PRI": "Puerto Rico",
		"QAT": "Qatar",
		"REU": "Reunion",
		"ROU": "Romania",
		"RUS": "Russian",
		"RWA": "Rwanda",
		"KNA": "Saint Kitts/Nevis",
		"LCA": "Saint Lucia",
		"VCT": "Saint Vincent and te Grenadines",
		"WSM": "Samoa",
		"SMR": "San Marino",
		"STP": "Sao Tome and Principe",
		"SAU": "Saudi Arabia",
		"SEN": "Senegal",
		"SRB": "Republic of Serbia",
		"SYC": "Seychelles",
		"SLE": "Sierra Leone",
		"SGP": "Singapore",
		"SVK": "Slovakia",
		"SVN": "Slovenia",
		"SLB": "Solomon Islands",
		"SOM": "Somalia",
		"ZAF": "South Africa",
		"SGS": "South Georgia",
		"ESP": "Spain",
		"LKA": "Sri Lanka",
		"SHN": "St. Helena",
		"SPM": "St. Pierre and Miquelon",
		"SDN": "Sudan",
		"SUR": "Suriname",
		"SJM": "Svalbard",
		"SWZ": "Swaziland",
		"SWE": "Sweden",
		"CHE": "Switzerland",
		"SYR": "Syrian",
		"TWN": "Taiwan",
		"TJK": "Tajikistan",
		"TZA": "Tanzania",
		"THA": "Thailand",
		"TLS": "Timor-leste",
		"TGO": "Togo",
		"TKL": "Tokelau",
		"TON": "Tonga",
		"TTO": "Trinidad and Tobago",
		"TUN": "Tunisia",
		"TUR": "Turkey",
		"TKM": "Turkmenistan",
		"TCA": "Turks and Caicos Islands",
		"TUV": "Tuvalu",
		"UGA": "Uganda",
		"UKR": "Ukraine",
		"ARE": "United Arab Emirates",
		"GBR": "United Kingdom",
		"USA": "United States",
		"URY": "Uruguay",
		"UZB": "Uzbekistan",
		"VUT": "Vanuatu",
		"VEN": "Venezuela",
		"VNM": "Vietnam",
		"VGB": "Virgin Islands (British)",
		"VIR": "Virgin Islands (U.S.)",
		"WLF": "Wallis and Futuna Islands",
		"ESH": "Western Sahara",
		"YEM": "Yemen",
		"ZMB": "Zambia",
		"ZWE": "Zimbabwe",
	}
	return m
}
